security:
    providers:
        my_provider:
            entity: { class: App:User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path: /logout
                target: /
            logout_on_user_change: true

            guard:
                authenticators:
                    - App\Security\GoogleAuthenticator
                    - App\Security\FacebookAuthenticator
                entry_point: App\Security\GoogleAuthenticator

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }